# This configuration file defines general app settings

APP_NAME: Pragmatic BIM Requirements Manager
ORGANISATION_NAME: Template_Organisation #change this to access the organisation specific content like translation files. Same name as folder in ´organisation_data\´

# Set to "true" if using Azure Blob for storage and "false" for local storage
USE_AZURE_STORAGE: false

MAIN_LANGUAGE: "DE"

# Manuly set the pages, so that they can be translated aswell
pages:
  home: home.py
  requirements: 1_requirements.py
  admin: 2_admin.py
  help: 9_help.py

# Available languages for the frontend, with their codes and names
FRONTEND_LANGUAGES:
  EN: "English"
  DE: "Deutsch"
  FR: "Français"
  IT: "Italiano"

# Configuration for columns and their corresponding widths for the formated excel export
contract_excel_columns:
  'FileName*': 15
  'ModelName*': 20
  'ElementName*': 20
  'ElementDescription*': 55
  'IfcEntityIfc4.0Name': 20
  'Pset': 35
  'AttributeDescription*': 45
  'AttributeName': 20
  'Unit': 15
  'DataTyp': 20
  'AllowedValues*': 45
  'ContainedIn*': 25
  '11': 8  # Change if the Phases are named differently
  '21': 8  # TODO #8 find better logic that works for all cases
  '22': 8
  '31': 8
  '32': 8
  '33': 8
  '41': 8
  '51': 8
  '52': 8
  '53': 8
  '61': 8
  '62': 8

#Variables to replace values in the csv programatically. Use this to set projcet specific values
VARIABLES:
  PROJECT_NUMBER : "{Projektnummer}"
  PROJECT_NAME : "{Projektname}"

#Necessary columns in the import data
required_workflows_columns:
  - WorkflowID
  - WorkflowName*
  - WorkflowDescription*
  - Status

required_models_columns:
  - ModelID
  - ModelName*
  - ModelDescription*
  - FileName*
  - SortModels

required_elements_columns:
  - ElementID
  - ElementName*
  - SortElement
  - IfcEntityIfc4.0Name
  - ElementDescription*
  - ImageName

required_attributes_columns:
  - AttributeID
  - AttributeName
  - SortAttribute
  - AttributeDescription*
  - Pset
  - AllowedValues*
  - RegexCheck*
  - DataTyp
  - Unit
  - IFC2x3
  - IFC4
  - IFC4.3
  - Applicability
  - ElementID
  - ModelID
  - WorkflowID

