[server]
headless = true
enableCORS = false
enableXsrfProtection = false
port = 8501


[theme]
primaryColor = "#4A90E2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFCF71"
textColor = "#262730"
font = "sans serif"

[browser]
gatherUsageStats = true

[client]
showSidebarNavigation = false

[layout]
layout = "wide"